### PR TITLE
Add Cargo.lock

### PR DESCRIPTION
**Pull request by fufexan**
On [Nix](https://nixos.org), in order to build Rust packages, we need the Cargo.lock. Also, it's good practice to include it, according to https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html. I'm not sure what the reason for not including the lockfile is, as I couldn't find any related issue from the past.

Specific section
> If you’re building an end product, which are executable like command-line tool or an application, or a system library with crate-type of staticlib or **cdylib**, check Cargo.lock into git.

### CODE REVIEW

**Comment by trinaldi** [comment]
Just a heads-up, you also need to remove the `Cargo.lock` from `.gitignore` otherwise the file won't be `push`ed in later changes.

**Comment by fufexan** [comment]
@trinaldi oh yeah, I thought I've done that already. Thanks for pointing it out :smile:

**Comment by fufexan** [comment]
Seems like it was removed, but the `.gitignore` file didn't get in the commit.

**Comment by trinaldi** [comment]
Those 2 messages above yours seems to be OK.

**Pull request merged**
